[package]
name = "remnantsofsiren/projectilecaster"
version = "0.1.9"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["test", "Packages", "build", "test.project.json", "selene.toml", "README.md", ".gitignore", ".vscode"]
description = """
    I wouldn't advice using this for production use, at the moment. Extremely experimental and only being uploaded for my own personal projects.
    Server/Client based projectile hit detection.

    API: https://remnantsofsiren.github.io/ProjectileCaster
    --> you will need to just require the module on the client in-order for things to render. Prior I used emitLegacyScripts however it caused bytenet to throw issues
"""

[dependencies]
Trove = "sleitnick/trove@1.5.0"
Signal = "data-oriented-house/lemonsignal@1.10.0"
ByteNet = "elitriare/bytenet-max@0.1.9"